package healthylifestyle;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.*;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class reminder extends javax.swing.JFrame {

    int y, m, d, hr, min, sec;
    int flag = 0;
    String s;
               
    public reminder() {
       
        initComponents();
        setLocationRelativeTo(null);
        setTitle("  HEALTHY LIFESTYLE  ");
        DateFormat timef = new SimpleDateFormat("HH:mm:ss");
        // SHOW_CURRENT_DATE.setText("     "+day+" - "+month+" - "+yr);

        ActionListener time = new ActionListener() {
            public void actionPerformed(ActionEvent t) {
                Date da = new Date();
                int day = da.getDate();
                int month = da.getMonth() + 1;
                int yr = Year.now().getValue();
                int hour = da.getHours();
                int minutes = da.getMinutes();
                int seconds = da.getSeconds();
                String current_time = da.toString();
                SHOW_CURRENT_DATE.setText("            " + current_time);
                if (flag == 1) {
                    if (yr == y && day == d && month == m && hour == hr && minutes == min && seconds == sec) {//if(hour==hr && minutes==min && seconds==sec)
                        {
                            System.out.println("entered");
                            JOptionPane.showMessageDialog(null, s, "REMINDER", JOptionPane.PLAIN_MESSAGE);

                            flag = 0;
                        }
                    }
                }
            }
        };
        Timer times = new Timer(1000, time);
        times.setInitialDelay(0);
        times.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SHOW_CURRENT_DATE = new javax.swing.JTextField();
        year_field = new javax.swing.JTextField();
        month_field = new javax.swing.JTextField();
        date_field = new javax.swing.JTextField();
        OK = new javax.swing.JButton();
        back = new javax.swing.JButton();
        message_tfld = new javax.swing.JTextField();
        hr_fld = new javax.swing.JTextField();
        min_fld = new javax.swing.JTextField();
        sec_fld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 850));
        setResizable(false);
        getContentPane().setLayout(null);

        SHOW_CURRENT_DATE.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        SHOW_CURRENT_DATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOW_CURRENT_DATEActionPerformed(evt);
            }
        });
        getContentPane().add(SHOW_CURRENT_DATE);
        SHOW_CURRENT_DATE.setBounds(390, 140, 490, 60);

        year_field.setText("2019");
        getContentPane().add(year_field);
        year_field.setBounds(680, 390, 70, 50);

        month_field.setText("03");
        getContentPane().add(month_field);
        month_field.setBounds(590, 390, 70, 50);

        date_field.setText("21");
        date_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(date_field);
        date_field.setBounds(510, 390, 70, 50);

        OK.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        OK.setText("SAVE");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(580, 620, 90, 33);

        back.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        back.setText("<back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(20, 20, 61, 27);

        message_tfld.setText("set a message");
        getContentPane().add(message_tfld);
        message_tfld.setBounds(400, 480, 500, 60);

        hr_fld.setText("hr");
        hr_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hr_fldActionPerformed(evt);
            }
        });
        getContentPane().add(hr_fld);
        hr_fld.setBounds(510, 320, 70, 50);

        min_fld.setText("min");
        min_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min_fldActionPerformed(evt);
            }
        });
        getContentPane().add(min_fld);
        min_fld.setBounds(590, 320, 70, 50);

        sec_fld.setText("sec");
        sec_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec_fldActionPerformed(evt);
            }
        });
        getContentPane().add(sec_fld);
        sec_fld.setBounds(680, 320, 70, 50);

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jLabel3.setText("     REMIND me at ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 260, 330, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthylifestyle/REminderbg.PNG"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1036, 869));
        jLabel1.setMinimumSize(new java.awt.Dimension(1036, 869));
        jLabel1.setPreferredSize(new java.awt.Dimension(1036, 869));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -110, 1036, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SHOW_CURRENT_DATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOW_CURRENT_DATEActionPerformed

    }//GEN-LAST:event_SHOW_CURRENT_DATEActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        flag = 1;
        y = Integer.parseInt(year_field.getText());
        m = Integer.parseInt(month_field.getText());
        d = Integer.parseInt(date_field.getText());
        s = message_tfld.getText();
        hr = Integer.parseInt(hr_fld.getText());
        min = Integer.parseInt(min_fld.getText());
        sec = Integer.parseInt(sec_fld.getText());

    }//GEN-LAST:event_OKActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        menu m = new menu();
        m.setVisible(true);
        new reminder().setVisible(false);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void date_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_fieldActionPerformed

    private void hr_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hr_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hr_fldActionPerformed

    private void min_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_min_fldActionPerformed

    private void sec_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sec_fldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reminder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    private javax.swing.JTextField SHOW_CURRENT_DATE;
    private javax.swing.JButton back;
    private javax.swing.JTextField date_field;
    private javax.swing.JTextField hr_fld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField message_tfld;
    private javax.swing.JTextField min_fld;
    private javax.swing.JTextField month_field;
    private javax.swing.JTextField sec_fld;
    private javax.swing.JTextField year_field;
    // End of variables declaration//GEN-END:variables
}
