
package healthylifestyle;
import java.io.*;
import java.lang.*;


public class tips extends javax.swing.JFrame {

    /**
     * Creates new form tips
     */
    int age,ans;
    String tips;
    public tips() {
        initComponents();
         setLocationRelativeTo(null);
         setTitle("  HEALTHY LIFESTYLE  ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 850));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("Suggestion ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 80, 219, 78);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 220, 700, 390);

        jButton2.setText("<back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 70, 120, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthylifestyle/Healthy-lifestyle-image.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-260, 10, 2530, 940);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // age=jTextField1.getText();
       //  ans=jTextField1.getText();
       // String s=jTextField1.getText();
        
         try
        {
            int c;
            FileReader info=new FileReader("user_information.txt");
            while((c=info.read())!=-1)
            {
                System.out.println((char)c);
            }
            info.close();
        }catch(Exception e)
        {
            System.out.println(e);
            
        }
        
        
        
        if(age<=18||ans<=24)
        {
            //StringBuffer s1=new StringBuffer("Eat less caloric food");
            //jTextField1.setText(s1);
                  //  StringBuffer s2=new StringBuffer("Do 30 minutes workout");
                    //j
            String s="Eat less caloric food\n\n\n\n"+"\n\nDo 30 minute workout\n\n\n\n" +"\n\nTake 15 mintues deep meditation\n\n\n\n" + "\n\nsleep early\n\n\n\n";
            jTextField1.setText(s);
           //jTextField1.setText("Eat less caloric food");
           // jTextField1.setText("Do 30 minute workout");
          //  jTextField1.setText("Take 15 mintues deep meditation");
          //  jTextField1.setText("sleep early");
        }
        else if(age<=50||ans<=29)
        {
            String s="Have low fat,low sugar food\n\n\n\n"+"\n\ndo 1 or 2 hours aerobic activity\n\n\n\n"+"\n\nTake 20 mintues deep meditation\n\n\n\n"+"sleep atleast 8 hours";
            jTextField1.setText(s);
            //jTextField1.setText("do 1 or 2 hours aerobic acti
            //jTextField1.setText("vity");
            //jTextField1.setText("Take 20 mintues deep meditation");
           // jTextField1.setText("sleep atleast 8 hours");
        }
        else if(age<=85||ans<=34)
        {
            String s="avoid fiber rich,low fat food\n\n\n\n"+"Stay physically active with regular exercise\n\n\n\n"+"Take all meditation directed by your doctor\n\n\n\n"+"Get sleep that your body needs\n\n\n\n";
            jTextField1.setText(s);
            
           //  jTextField1.setText("avoid fiber rich,low fat food");
           // jTextField1.setText("Stay physically active with regular exercise");
           // jTextField1.setText("Take all meditation directed by your doctor");
           // jTextField1.setText("Get sleep that your body needs");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        newSubmit11 m=new newSubmit11();
        m.setVisible(true);
        new tips().setVisible(false);
         dispose();
         
         
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tips().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
